language: generic 
sudo: requierd
services: 
  - docker


before_install:
  - docker build -t adiellevy/docker-react -f dockerfile.dev .


script:
  - docker run -e CI=true adiellevy/docker-react npm run test



